[package]
name = "event-journal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
muxport-protocol = { path = "../muxport-protocol" }
rusqlite = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
