[package]
name = "muxport-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"
